recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
    mac_os_x:
        - applications::sublime_text_3
        - applications::gnu-tar
        - osxdefaults::set_terminal_profile
attributes:
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
        cask_apps:
            - puppet
        gems:
            - librarian-puppet
            - vagrant
            - virtualbox

